FB-627 ImmutableX collections
rarible/union-service pull request #184
Opened 2022-03-11 08:24 UTC by atapin

2022-03-11 08:27 UTC, zolt requested changes

2022-03-11 08:27 UTC, zolt commented on integration/immutablex/src/main/kotlin/com/rarible/protocol/union/integration/immutablex/client/ImmutablexApiClient.kt
> +    val collectionsApi = CollectionsApi(webClient)
private

2022-03-11 09:50 UTC, atapin commented on integration/immutablex/src/main/kotlin/com/rarible/protocol/union/integration/immutablex/client/ImmutablexApiClient.kt
> +    val collectionsApi = CollectionsApi(webClient)
it's used as `client.collectionsApi.getAll(continuation, size)`

2022-03-14 04:22 UTC, zolt approved these changes

2022-03-14 04:24 UTC, merged