ALPHA-498 reindex collections
rarible/union-service pull request #318
Opened 2022-05-23 06:21 UTC by atapin

2022-05-24 12:08 UTC, augur commented
Tests failed on Jenkins

2022-05-24 12:09 UTC, augur commented
I can't find where this code is launched from

2022-05-25 12:22 UTC, augur commented
Consider targeting this to 1.27

2022-05-27 06:45 UTC, augur commented on worker/src/main/kotlin/com/rarible/protocol/union/worker/task/search/ReindexService.kt
>                  // EsEntity.COLLECTION,
Remove this please

2022-06-10 08:36 UTC, zolt requested changes

2022-06-10 08:36 UTC, zolt commented on worker/src/main/kotlin/com/rarible/protocol/union/worker/task/search/collection/CollectionTaskParam.kt
> +class CollectionTaskParam(
looks like data class

2022-06-10 09:00 UTC, zolt approved these changes

2022-06-10 09:46 UTC, merged