PT-708 fixed incorrect activities results for SELL and TRANSFER_TO
rarible/union-service pull request #426
Opened 2022-07-18 05:15 UTC by atapin

2022-07-18 05:32 UTC, zolt approved these changes

2022-07-18 06:09 UTC, s-yurov approved these changes

2022-07-18 06:42 UTC, augur commented
1.30 has been released already, so let's target it there

2022-07-18 06:42 UTC, augur requested changes

2022-07-18 06:42 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +    fun finalize(): UserFilters {
Name is ambiguous

2022-07-18 06:42 UTC, augur commented on api/src/test/kotlin/com/rarible/protocol/union/api/controller/ActivityControllerElasticFt.kt
> +
We should also check that other activities with same type but different users role are filtered out

2022-07-18 06:42 UTC, augur commented on api/src/test/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverterTest.kt
> +            val userActivityTypes = listOf(UserActivityTypeDto.TRANSFER_FROM, UserActivityTypeDto.SELL)
What about buy / transfer_to cases?

2022-07-18 06:42 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +            in listOf(UserActivityTypeDto.BUY, UserActivityTypeDto.TRANSFER_TO) -> {
What if types are mixed? (Having both BUY and SELL)

2022-07-20 06:17 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +            in listOf(UserActivityTypeDto.BUY, UserActivityTypeDto.TRANSFER_TO) -> {
this is covered by `UsersFilter.finalize()`

2022-07-20 06:50 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +    fun finalize(): UserFilters {
added a comment

2022-07-20 06:52 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +            in listOf(UserActivityTypeDto.BUY, UserActivityTypeDto.TRANSFER_TO) -> {
`when` block only executes first matching case, others are skipped, so in case both SELL and BUY `toUsers` will remain empty, is it ok?

2022-07-20 06:54 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +            in listOf(UserActivityTypeDto.BUY, UserActivityTypeDto.TRANSFER_TO) -> {
in this case we will match by `anyUsers`. they are populated by the method previously mentioned

2022-07-20 07:02 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +    fun finalize(): UserFilters {
I mean it has the same name as `Object Class method that is used to perform cleanup activity before destroying any object`

2022-07-21 04:46 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +    fun finalize(): UserFilters {
got you. fixed

2022-07-21 04:46 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/ActivityFilterConverter.kt
> +            in listOf(UserActivityTypeDto.BUY, UserActivityTypeDto.TRANSFER_TO) -> {
added tests

2022-07-21 06:05 UTC, augur approved these changes

2022-07-21 06:05 UTC, merged