PT-443 es orders controllers
rarible/union-service pull request #436
Opened 2022-07-25 07:58 UTC by atapin

2022-07-25 11:01 UTC, augur requested changes

2022-07-25 11:01 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/EsOrderFilter.kt
> +
Lets add integration tests on these filters, as in other entities

2022-07-27 06:57 UTC, augur commented
should be pointed to master, I believe

2022-08-01 05:23 UTC, atapin commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/EsOrderFilter.kt
> +            if(platform != null) {
currently it's not possible to reuse the util function, as it's located in enrichment module. let's stay with builders approach for now

2022-08-01 05:24 UTC, atapin commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/EsOrderFilter.kt
> +
done

2022-08-01 05:24 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
> +        return if(esOrders.isEmpty()) {
what do you mean?

2022-08-01 05:26 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
>  }
repository integration tests should cover the main logic

2022-08-01 06:08 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
>  }
Meanwhile, repository tests:
https://github.com/rarible/union-service/blob/0ab261240df885e10593d24753cd3cf0e1ea2390/indexer/src/test/kotlin/com/rarible/protocol/union/search/indexer/repository/EsOrderRepositoryFt.kt
Maybe you're talking about some others?

2022-08-01 06:10 UTC, augur commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
> +        return if(esOrders.isEmpty()) {
I mean that orders `esOrders` are returned from ES in specific sorting, but during `orderIdsByBlockchain.flatMapAsync` this sorting breaks, whereas it has to be maintained

2022-08-01 06:47 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
>  }
fixed

2022-08-01 06:48 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
> +        return if(esOrders.isEmpty()) {
fixed

2022-08-01 07:10 UTC, augur commented on enrichment/src/main/kotlin/com/rarible/protocol/union/enrichment/repository/search/ElasticSearchRepository.kt
> +    suspend fun deleteAll() {
It was discussed previously that it is dangerous to have such method, though solely for tests.
How we deal with it for other entities?

2022-08-07 15:26 UTC, atapin commented on enrichment/src/main/kotlin/com/rarible/protocol/union/enrichment/repository/search/ElasticSearchRepository.kt
> +    suspend fun deleteAll() {
is was supposed to be removed. removed now

2022-08-07 15:31 UTC, atapin commented on api/src/main/kotlin/com/rarible/protocol/union/api/service/elastic/OrderElasticService.kt
> +        val sortedOrders = esOrders.map { slices[it.orderId]!! }
fixed

2022-08-07 15:31 UTC, atapin commented on core/src/main/kotlin/com/rarible/protocol/union/core/FeatureFlagsProperties.kt
> +    var orderRefreshPolicy: WriteRequest.RefreshPolicy = WriteRequest.RefreshPolicy.NONE,
fixed

2022-08-08 08:19 UTC, augur approved these changes

2022-08-08 08:20 UTC, merged