Pt 730
rarible/union-service pull request #445
Opened 2022-07-29 04:25 UTC by s-yurov

2022-07-29 05:15 UTC, atapin approved these changes

2022-07-29 07:54 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/EsHelper.kt
> +//        writeIndex: Boolean
do we need this commented out code?

2022-07-29 07:54 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/IndexService.kt
> +            throw RuntimeException("Index ${definition.entity} exists with name $realIndexName but metadata does not. Update metadata")
Why should it throw exception? Metadata is updated above?

2022-07-29 07:54 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/bootstrap/ElasticsearchBootstrapper.kt
> +            currentEntityMetadata.mapping != definition.mapping -> {
in case both mapping and settings are changed, only this piece of code will be executed

2022-07-29 07:54 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/elasticsearch/EntityDefinition.kt
> +fun md5(input: String): String {
Doesn't seem to belong here.
Let's at least make it private

2022-07-29 07:54 UTC, augur commented on cicd/deploy/dev.yaml
> -protocol-union-indexer:
why?

2022-07-29 07:54 UTC, augur commented on indexer/src/test/kotlin/com/rarible/protocol/union/search/indexer/repository/EsActivityQueryBuilderServiceIntegrationTest.kt
> +        repository.refresh()
This looks quite ugly. Can we have some built-in immediate save for tests?

2022-07-29 07:54 UTC, augur commented on indexer/src/test/kotlin/com/rarible/protocol/union/search/indexer/repository/EsItemRepositoryFt.kt
> +        val id = repository.save(esItem).itemId
I suppose we can delete `createIndex` and `createAlias `, and this test will still pass, doesn't look good

2022-07-29 07:54 UTC, augur commented on worker/src/test/kotlin/com/rarible/protocol/union/worker/bootstrap/ElasticsearchBootstrapperTest.kt
> +    private val loadMapping = "{\n" +
can `"""  ...  """` be used here?

2022-07-29 08:27 UTC, atapin requested changes

2022-07-29 08:27 UTC, atapin commented on core/src/test/kotlin/com/rarible/protocol/union/core/es/ElasticsearchTestBootstrapper.kt
> +            .map { index ->
use `mapAsync` please. it reduces amount of nested code chunks

2022-07-29 08:27 UTC, atapin commented on core/src/test/kotlin/com/rarible/protocol/union/core/es/ElasticsearchTestBootstrapper.kt
> +                async {
`mapAsync`

2022-07-29 12:01 UTC, s-yurov commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/IndexService.kt
> +            throw RuntimeException("Index ${definition.entity} exists with name $realIndexName but metadata does not. Update metadata")
+

2022-07-29 12:15 UTC, s-yurov commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/EsHelper.kt
> +//        writeIndex: Boolean
+

2022-07-29 12:23 UTC, s-yurov commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/elasticsearch/EntityDefinition.kt
> +fun md5(input: String): String {
+

2022-07-29 12:23 UTC, s-yurov commented on core/src/main/kotlin/com/rarible/protocol/union/core/model/elasticsearch/EntityDefinition.kt
> +fun md5(input: String): String {
+

2022-07-29 12:58 UTC, s-yurov commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/bootstrap/ElasticsearchBootstrapper.kt
> +            currentEntityMetadata.mapping != definition.mapping -> {
fixed

2022-07-29 13:53 UTC, augur commented on core/src/main/kotlin/com/rarible/protocol/union/core/elasticsearch/IndexService.kt
> +            throw RuntimeException("Index ${definition.entity} exists with name $realIndexName but metadata does not. Update metadata")
Sorry, I don't get what was changed

2022-07-29 14:18 UTC, atapin approved these changes

2022-08-16 04:53 UTC, s-yurov commented on worker/src/test/kotlin/com/rarible/protocol/union/worker/bootstrap/ElasticsearchBootstrapperTest.kt
> +    private val loadMapping = "{\n" +
+

2022-08-16 05:04 UTC, s-yurov commented on indexer/src/test/kotlin/com/rarible/protocol/union/search/indexer/repository/EsActivityQueryBuilderServiceIntegrationTest.kt
> +        repository.refresh()
delted

2022-08-16 05:04 UTC, s-yurov commented on indexer/src/test/kotlin/com/rarible/protocol/union/search/indexer/repository/EsItemRepositoryFt.kt
> +        val id = repository.save(esItem).itemId
yes this test is not working, I deleted

2022-08-16 05:04 UTC, s-yurov commented on worker/src/test/kotlin/com/rarible/protocol/union/worker/bootstrap/ElasticsearchBootstrapperTest.kt
> +    private val loadMapping = "{\n" +
fixed

2022-08-16 05:04 UTC, s-yurov commented on core/src/test/kotlin/com/rarible/protocol/union/core/es/ElasticsearchTestBootstrapper.kt
> +            .map { index ->
fixed

2022-08-16 05:05 UTC, s-yurov commented on core/src/test/kotlin/com/rarible/protocol/union/core/es/ElasticsearchTestBootstrapper.kt
> +                async {
fixed

2022-08-16 06:11 UTC, augur approved these changes

2022-08-16 18:35 UTC, merged